import sqlite3
conn = sqlite3.connect('data/bubblemate.db')
c = conn.cursor()
c.execute("SELECT DATE('now')")
print(f'当前日期: {c.fetchone()[0]}')
c.execute("SELECT DATE('2026-07-07 04:15:49')")
print(f'解析日期: {c.fetchone()[0]}')
c.execute("SELECT COUNT(*) FROM complaints WHERE DATE(created_at) = DATE('now')")
print(f'今日投诉: {c.fetchone()[0]}')
c.execute("SELECT COUNT(*) FROM complaints WHERE resolved = 1")
print(f'已解决: {c.fetchone()[0]}')
c.execute("SELECT COUNT(*) FROM complaints")
print(f'总数: {c.fetchone()[0]}')
conn.close()